### ISSUE TITLE
Add Web Console Tab as website type with ${_SANDBOX_ID} param

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#62]
We can have the support for a Web Console Tab using this env: `${_SANDBOX_ID}`

So the snippet would be:

```
 tabs:
  - title: Web Console
    type: website
    url: https://console-openshift-console.crc-dzk9v-master-0.crc.${_SANDBOX_ID}.instruqt.io
    new_window: true
```
